export const dataSubjects =
  [{ subjects: [
    { name: 'Mecânica e Ondas',
      icon: 'mo.png',
      id: 7,
      category: '1º Ano 1º Semestre',
      links: [
        {
          name: 'Página da Cadeira',
          url: 'https://fenix.tecnico.ulisboa.pt/disciplinas/MO4517/2015-2016/1-semestre',
        },
      ],
    },
    { name: 'Álgebra Linear',
      icon: 'al.png',
      id: 8,
      category: '1º Ano 1º Semestre',
      links: [
        {
          name: 'Página da Cadeira',
          url: 'https://fenix.tecnico.ulisboa.pt/disciplinas/AL174517/2015-2016/1-semestre',
        },
      ],
    },
    { name: 'Cálculo Diferencial e Integral 1',
      icon: 'cdi1.png',
      id: 9,
      category: '1º Ano 1º Semestre',
      links: [
        {
          name: 'Página da Cadeira',
          url: 'https://fenix.tecnico.ulisboa.pt/disciplinas/CDI72517/2015-2016/1-semestre/',
        },
      ],
    },
    { name: 'Cálculo Diferencial e Integral 2',
      icon: 'cdi1.png',
      id: 10,
      category: '1º Ano 2º Semestre',
      links: [
        {
          name: 'Página da Cadeira',
          url: 'https://fenix.tecnico.ulisboa.pt/disciplinas/CDI13451113/2015-2016/2-semestre/',
        },
      ],
    },
    { name: 'Mecânica Geral',
      icon: 'mg.png',
      id: 11,
      category: '1º Ano 2º Semestre',
      links: [
        {
          name: 'Página da Cadeira',
          url: 'https://fenix.tecnico.ulisboa.pt/disciplinas/MGer64/2012-2013/2-semestre/',
        },
      ],
    },
    { name: 'Análise Complexa e Equações Diferenciais',
      icon: 'aced.png',
      id: 12,
      category: '2º Ano 1º Semestre',
      links: [
        {
          name: 'Página da Cadeira',
          url: 'https://fenix.tecnico.ulisboa.pt/disciplinas/ACED1325179/2016-2017/1-semestre/',
        },
      ],
    },
    { name: 'Matemática Computacional',
      icon: 'mc.png',
      id: 13,
      category: '2º Ano 1º Semestre',
      links: [
        {
          name: 'Página da Cadeira',
          url: 'https://fenix.tecnico.ulisboa.pt/disciplinas/MC245179/2016-2017/1-semestre/',
        },
      ],
    },
    { name: 'Termodinâmica',
      icon: 'termo.png',
      id: 14,
      category: '2º Ano 1º Semestre',
      links: [
        {
          name: 'Página da Cadeira',
          url: 'https://fenix.tecnico.ulisboa.pt/disciplinas/TEM179/2016-2017/1-semestre',
        },
      ],
    },
    { name: 'Eletromagnetismo',
      icon: 'eo.png',
      id: 15,
      category: '2º Ano 2º Semestre',
      links: [
        {
          name: 'Página da Cadeira',
          url: 'https://fenix.tecnico.ulisboa.pt/disciplinas/EO33645111326-2/2016-2017/2-semestre',
        },
      ],
    },
    { name: 'Mecânica Analítica',
      icon: 'mana.png',
      id: 16,
      category: '2º Ano 2º Semestre',
      links: [
        {
          name: 'Página da Cadeira',
          url: 'https://fenix.tecnico.ulisboa.pt/disciplinas/MAna3645111326/2016-2017/2-semestre',
        },
      ],
    },
    { name: 'Probabilidade e Estatística',
      icon: 'pe.png',
      id: 17,
      category: '2º Ano 2º Semestre',
      links: [
        {
          name: 'Página da Cadeira',
          url: 'https://fenix.tecnico.ulisboa.pt/disciplinas/PEst636410111326/2016-2017/2-semestre',
        },
      ],
    },
    { name: 'Eletrodinâmica Clássica',
      icon: 'ecla.png',
      id: 18,
      category: '3º Ano 1º Semestre',
      links: [
        {
          name: 'Página da Cadeira (2018)',
          url: 'https://fenix.tecnico.ulisboa.pt/disciplinas/ECla57/2018-2019/1-semestre',
        },
        {
          name: 'Página da Cadeira',
          url: 'https://fenix.tecnico.ulisboa.pt/disciplinas/ECla5/2017-2018/1-semestre',
        },
      ],
    },
    { name: 'Física dos Meios Contínuos',
      icon: 'fmc.png',
      id: 19,
      category: '3º Ano 1º Semestre',
      links: [
        {
          name: 'Página da Cadeira',
          url: 'https://fenix.tecnico.ulisboa.pt/disciplinas/FMCon5/2017-2018/1-semestre',
        },
      ],
    },
    { name: 'Técnicas Matemáticas da Física',
      icon: 'tmf.png',
      id: 20,
      category: '3º Ano 1º Semestre',
      links: [
        {
          name: 'Página da Cadeira',
          url: 'https://fenix.tecnico.ulisboa.pt/disciplinas/TMF5/2017-2018/1-semestre',
        },
      ],
    },
    { name: 'Mecânica Quântica 1',
      icon: 'mq1.png',
      id: 21,
      category: '3º Ano 1º Semestre',
      links: [
        {
          name: 'Página da Cadeira',
          url: 'https://fenix.tecnico.ulisboa.pt/disciplinas/MQ5/2017-2018/1-semestre',
        },
      ],
    },
    { name: 'Mecânica Quântica 2',
      icon: 'mq2.png',
      id: 22,
      category: '3º Ano 2º Semestre',
      links: [
        {
          name: 'Página da Cadeira',
          url: 'https://fenix.tecnico.ulisboa.pt/disciplinas/MQ-II/2017-2018/2-semestre',
        },
      ],
    },
    { name: 'Física do Estado Sólido',
      icon: 'fes.png',
      id: 23,
      category: '3º Ano 2º Semestre',
      links: [
        {
          name: 'Página da Cadeira',
          url: 'https://fenix.tecnico.ulisboa.pt/disciplinas/FES/2017-2018/2-semestre',
        },
      ],
    },
    { name: 'Física Estatística',
      icon: 'festa.png',
      id: 24,
      category: '3º Ano 2º Semestre',
      links: [
        {
          name: 'Página da Cadeira',
          url: 'https://fenix.tecnico.ulisboa.pt/disciplinas/FEsta/2017-2018/2-semestre',
        },
      ],
    },
    { name: 'Astrofísica',
      icon: 'astro.png',
      id: 25,
      category: '4º Ano 1º Semestre',
      links: [
        {
          name: 'Página da Cadeira',
          url: 'https://fenix.tecnico.ulisboa.pt/disciplinas/Ast57/2018-2019/1-semestre',
        },
      ],
    },
    { name: 'Física de Partículas',
      icon: 'particle.png',
      id: 26,
      category: '4º Ano 1º Semestre',
      links: [
        {
          name: 'Página da Cadeira',
          url: 'https://fenix.tecnico.ulisboa.pt/disciplinas/FPar57/2018-2019/1-semestre',
        },
      ],
    },
    { name: 'Introdução à Investigação',
      icon: 'invest.png',
      id: 27,
      category: '4º Ano 1º Semestre',
      links: [
        {
          name: 'Página da Cadeira',
          url: 'https://fenix.tecnico.ulisboa.pt/disciplinas/II57/2018-2019/1-semestre',
        },
      ],
    },
    { name: 'Ótica e Lasers',
      icon: 'optics.png',
      id: 28,
      category: '4º Ano 1º Semestre',
      links: [
        {
          name: 'Página da Cadeira',
          url: 'https://fenix.tecnico.ulisboa.pt/disciplinas/OL7/2018-2019/1-semestre',
        },
      ],
    },
    { name: 'Mecânica Geométrica',
      icon: 'mgeom.png',
      id: 29,
      category: '4º Ano 1º Semestre',
      links: [
        {
          name: 'Página da Cadeira',
          url: 'https://www.math.tecnico.ulisboa.pt/~jnatar/MG-18/',
        },
        {
          name: 'Página do Fénix',
          url: 'https://fenix.tecnico.ulisboa.pt/disciplinas/MG2517957/2018-2019/1-semestre',
        },
      ],
    },
    { name: 'Física dos Plasmas',
      icon: 'plasmas.png',
      id: 30,
      category: '5º Ano 1º Semestre',
      links: [
        {
          name: 'Página da Cadeira',
          url: 'https://fenix.tecnico.ulisboa.pt/disciplinas/FTP577/2019-2020/1-semestre',
        },
      ],
    },
    { name: 'CMQ',
      icon: 'cmq.png',
      id: 31,
      category: '5º Ano 1º Semestre',
      links: [
        {
          name: 'Página da Cadeira',
          url: 'https://fenix.tecnico.ulisboa.pt/disciplinas/CMQ577/2019-2020/1-semestre',
        },
      ],
    },
    { name: 'Empreendedorismo',
      icon: 'eigc.png',
      id: 32,
      category: '5º Ano 1º Semestre',
      links: [
        {
          name: 'Página da Cadeira',
          url: 'https://fenix.tecnico.ulisboa.pt/disciplinas/EIGC77/2019-2020/1-semestre',
        },
      ],
    },
    { name: 'Mecânica Quântica Matemática',
      icon: 'mqm.png',
      id: 33,
      category: '5º Ano 1º Semestre',
      links: [
        {
          name: 'Página da Cadeira',
          url: 'https://fenix.tecnico.ulisboa.pt/disciplinas/MQM77/2019-2020/1-semestre',
        },
      ],
    },
    { name: 'Outros Livros',
      icon: 'etc.png',
      id: 34,
      links: [],
    },
    { name: 'Teoria de Campo',
      icon: 'mqm.png',
      id: 35,
      category: '4º Ano 2º Semestre',
      links: [
        {
          name: 'Página da Cadeira',
          url: 'https://fenix.tecnico.ulisboa.pt/disciplinas/TCam/2018-2019/2-semestre',
        },
      ],
    },
    { name: 'Relatividade e Cosmologia',
      icon: 'mqm.png',
      id: 36,
      category: '4º Ano 2º Semestre',
      links: [
        {
          name: 'Página da Cadeira',
          url: 'https://fenix.tecnico.ulisboa.pt/disciplinas/RCos/2018-2019/2-semestre',
        },
      ],
    },
    { name: 'Física da Matéria Condensada',
      icon: 'mqm.png',
      id: 37,
      category: '4º Ano 2º Semestre',
      links: [
        {
          name: 'Página da Cadeira',
          url: 'https://fenix.tecnico.ulisboa.pt/disciplinas/FMC/2018-2019/2-semestre',
        },
      ],
    },
    { name: 'Modelo Standard e Nova Física',
      icon: 'mqm.png',
      id: 38,
      category: '4º Ano 2º Semestre',
      links: [
        {
          name: 'Página da Cadeira',
          url: 'https://fenix.tecnico.ulisboa.pt/disciplinas/MSNF/2018-2019/2-semestre',
        },
      ],
    },
  ],
  }];

// Page Categories
export const categories = ['1º Ano 1º Semestre',
  '1º Ano 2º Semestre',
  '2º Ano 1º Semestre',
  '2º Ano 2º Semestre',
  '3º Ano 1º Semestre',
  '3º Ano 2º Semestre',
  '4º Ano 1º Semestre',
  '4º Ano 2º Semestre',
  '5º Ano 1º Semestre',
  'Outros', // Default category for uncategorized subjects
];
